title: <p align="center"> Jiting (April) Jiang </p>

logo: "/images/jtjiang_profile_round.png?raw=true"

description:
  <p align="center">
  California, USA
  <br> (+1) 857-272-8515
  <br> jitingjt.jiang@outlook.com
  <br> <a href="pdf/Resume_Jiting_Jiang_profile.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jitingjiang/">LinkedIn</a> |
  <a href="https://github.com/jitingjiang">GitHub</a>  
  </p>
  
  <p align="justify">
  I am a well-trained data scientist and applied economist who is passionate about leveraging real-world data and statistical methods to drive meaningful impact. 
  <br><br>
  I am pursuing a doctorate degree in applied economics at University of California, Davis. I have proficiency in Python, SQL, and Stata, as well as expertise in Experiments, Causal Inference, Data Visualization and Machine Learning. 
  <br><br>
  I also pride myself on being detail-oriented, self-motivated, and highly organized. I am currently seeking opportunities related to Data Science. 
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

