title: <p align="center"> Jiting Jiang </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  California, USA
  <br> (+1) 8572728515
  <br> jiting.jiang@outlook.com
  <br> <a href="pdf/Carbone_Giorgio_CV_eng.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jitingjiang/">LinkedIn</a> |
  <a href="https://github.com/jitingjiang">GitHub</a>  
  </p>
  
  <p align="justify">
  I am a well-trained data scientist and applied economist who is passionate about leveraging real-world data and statistical methods to drive meaningful impact. 
  <br><br>
  I have 7+ years of experience in data collection and analysis in human behavior research. I specialize in using statistical and causal inference methods, including experiments, to inform decisions on economic policy using large datasets. I have proficiency in Python, SQL, and Stata, as well as expertise in Causal Inference, Data Visualization and Machine Learning. 
  <br><br>
  I am pursuing a doctorate degree in applied economics at University of California, Davis, where I receive solid training in Statistics, Econometrics, Machine Learning and more.
  <br><br>
  I also pride myself on being detail-oriented, self-motivated, and highly organized. I am currently seeking opportunities related to Data Science. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

